sudo: required
language: java
jdk: oraclejdk8
env:
  matrix:
    - DB=rdbms
    - DB=riak
services:
  - riak
  - postgresql
before_script:
  sh -c "if [ '$DB' = 'riak' ]; then sh devicehive-riak-dao/src/main/resources/riak-initial-data.sh; fi"
script: "mvn clean install -P undertow,booted-${DB}"
deploy:
  provider: releases
  api_key:
    secure: mGftdsPBwei6SaaSveH8KfQ1PH/SRv3fZDjSNZVZTRAhsgn0EwaTP0z0zkdVjqRJs4Q3AGlXObT6KgIky+gDDNb5kKYmQtNy26JgaFqdglyIVG3c4fM6mFPqOIToOrY6Won1PFj+9Od9G7C4ehv3/OJCL+p/XGG9ZV+vZCQlyXU=
  file_glob: true
  file: ${HOME}/build/${TRAVIS_REPO_SLUG}/target/*.jar
  skip_cleanup: true
  on:
    branch: 
     - staging
     - master
    tags: true
    repo: devicehive/devicehive-java-server
